### ISSUE TITLE
Contributor

### ISSUE THREAD

**Issue by Hitsuko** [ScarletxZ/Pandora-Engine#3]
You did tell me that I'll being a new contributor in this repo. Just a little poke, because it's not my style for being a duck that waits in their place without doing anything except staring peoples.

**Comment by ScarletxZ** [comment]
Lol, TY for the small poke. I'll make sure I add you to the list of contributors.. Maybe tomorrow or at least this night. Anything just get cramped here... Ugh, signal and night time sucks.
